jobs:
- name: build
  plan:
  - get: git
    trigger: true
  - params:
      build: git
      skip_download: true
      tag_as_latest: true
    put: docker
  serial: true
resources:
- name: docker
  source:
    password: ((gcr.private_key))
    repository: eu.gcr.io/halfpipe-io/halfpipe-docker-compose-with-cache
    username: _json_key
  type: docker-image
- name: git
  source:
    branch: with-cache
    private_key: ((github.private_key))
    uri: git@github.com:springernature/halfpipe-docker-compose.git
  type: git
