resources:
  - name: git
    type: git
    source:
      private_key: ((github.private_key))
      uri: git@github.com:springernature/halfpipe-docker-compose.git
      branch: with-cache
  - name: docker
    type: docker-image
    source:
      repository: eu.gcr.io/halfpipe-io/halfpipe-docker-compose-with-cache
      username: _json_key
      password: ((gcr.private_key))

jobs:
  - name: build
    serial: true
    plan:
      - get: git
        trigger: true
      - put: docker
        params:
          build: git
          tag_as_latest: true
          skip_download: true
