version: '3'
services:
  app:
    image: eu.gcr.io/halfpipe-io/build-bash
    command: bash -c 'ip a'
    working_dir: /root/code
    volumes:
      - .:/root/code
      - /var/halfpipe/shared-cache:/var/halfpipe/shared-cache
