version: '3'
services:
  app:
    image: appropriate/curl
    volumes:
    - .:/app
    command: curl --fail http://dependency/test.html 
    depends_on:
    - dependency

  dependency:
    image: nginx
    volumes:
    - ./src:/usr/share/nginx/html:ro
    ports:
    - "80:80"
