version: '3'
services:
  app:
    image: debian
    command: bash -c './test.sh'
    working_dir: /root/code
    volumes:
      - .:/root/code
      - /var/halfpipe/shared-cache:/var/halfpipe/shared-cache